language: node_js
node_js:
- "stable"

addons:
  apt:
    packages:
      - python3

stages:
  - Build

before_install:
  - pip3 install poetry
  - cd client
  - npm install
  - cd ../
  - chmod +x dev.sh

install:
  - poetry install

jobs:
  include:
    - stage: Build
