os: linux

language: python
python: 
  - "3.7.7"
dist: xenial

stages:
  - Build

before_install:
  - sudo apt update
  - nvm ls-remote
  - nvm install v12.6
  - pip install gdown
  - pip install poetry
  - pip install codecov
  - poetry shell
  - chmod +x dev.sh

install:
  - cd client
  - npm install
  - cd ../
  - gdown $CheckpointUrl -O checkpoint.tar.gz
  - tar -xvf checkpoint.tar.gz
  - mv checkpoint/* server/algorythm/checkpoint
  - rm -rf checkpoint.tar.gz checkpoint/
  - cd server && poetry install && cd ../

jobs:
  include:
    - stage: Build      
    - script: pytest tests.py && echo "Build success!"

after_success:
  - codecov
