language: python
dist: xenial
python:
  - "3.7"

stages:
  - Test

before_install:
  - pip install poetry && cd server

install:
  - poetry install

jobs:
  include:
    - stage: Test
      script: cd ../ && poetry run pytest tests.py
