language: python
dist: xenial
python:
  - "3.7.7"

stages:
  - Build

before_install:
  - pip install poetry
  - cd client
  - npm install
  - cd ../server
  - chmod +x dev.sh
  - cd ../

install:
  - poetry install

jobs:
  include:
    - stage: Build
      script: poetry shell && sh dev.sh
