os: linux

sudo: enabled

language: node_js
node_js:
- 12
dist: xenial

stages:
  - Build

before_install:
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt update
  - sudo apt install python3.7
  - pyenv global 3.7
  - chmod +x dev.sh

install:
  - cd client
  - npm install
  - cd ../
  - pip install gdown
  - pip install poetry
  - gdown $CheckpointUrl -O checkpoint.tar.gz
  - tar -xvf checkpoint.tar.gz
  - mv checkpoint/* server/algorythm/checkpoint
  - rm -rf checkpoint.tar.gz checkpoint/
  - poetry shell && cd server && poetry install && cd ../

jobs:
  include:
    - stage: Build      
    - script: pytest tests.py && echo "Build success!"
