language: python
dist: xenial
python:
  - "3.7"

stages:
  - Test

before_install:
  - pip install poetry && cd server

install:
  - poetry install

after_install:
  - cd ../

jobs:
  include:
    - stage: Test
      script: poetry run pytest tests.py
