script: ./test.py

language: python
dist: xenial
python:
  - "3.7"

stages:
  - Test

before_install:
  - pip install poetry

install:
  - poetry install

jobs:
  include:
    - stage: Test
      script: poetry run pytest tests.py
