language: python
dist: xenial
python:
  - "3.7.7"

stages:
  - Tests

before_install:
  - pip install poetry && cd server

install:
  - poetry install

jobs:
  include:
    - stage: Tests
      # script: cd ../ && poetry run pytest tests.py
      script: echo "Done"
